server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/training?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yq.myspringboot.pojo


