server:
  port: 80
  servlet:
    context-path: /crm
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3307/crm?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    static-path-pattern: /static/**

#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jad.po,com.jad.aop.po