server:
  port: 80



eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://activate.navicat.com:7001/eureka/,http://localhost:7002/eureka/
feign:
  hystrix:
    enabled: true