server:
  port: 80
  address: 0.0.0.0
person:
  name: LiLei
  age: 20
  dog:
    name: Hee
    age: 1

person2:
  name: Mike
  age: 23
  dog: {name:Mee,age:2}
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT

