server:
  port: 80
  address: 127.0.0.1
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  error:
    path: error.html
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
#    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
mybatis:
  type-aliases-package: com.ll.crm.pojo
  mapper-locations: classpath:mapper/*.xml

