server:
  port: 7001

eureka:
  instance:
    hostname: activate.navicat.com
  client:
    register-with-eureka: false  #标识注册中心注册自己
    fetch-registry: false  #false标识自己为注册中心
    service-url:
      #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群：（关联）
      defaultZone: http://localhost:7002/eureka/
